project:
  type: website
  output-dir: .

website:
  title: "Pablo Maximiliano"
  site-url: "/"
  navbar:
    left:
      - href: index.qmd
        text: CV
      - href: about.qmd
        text: Projects
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: solar
    css: styles.css
    toc: true